CREATE TABLE `conectores_api` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome` varchar(100) NOT NULL,
	`tipo` enum('monitoramento','consulta','intimacoes','diarios','distribuicao','webhook') NOT NULL,
	`baseUrl` varchar(500) NOT NULL,
	`endpoint` varchar(500) NOT NULL,
	`metodo` enum('GET','POST','PUT','DELETE','PATCH') NOT NULL,
	`descricao` text NOT NULL,
	`parametros` text,
	`exemploRequest` text,
	`exemploResponse` text,
	`headers` text,
	`autenticacao` varchar(100),
	`modulo` varchar(200),
	`ativo` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `conectores_api_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `intimacoes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`processoId` int NOT NULL,
	`clienteId` int,
	`tipo` enum('intimacao','citacao','audiencia','despacho','sentenca','acordao','publicacao') NOT NULL,
	`origem` varchar(100),
	`dataDisponibilizacao` timestamp,
	`dataLeitura` timestamp,
	`prazoFinal` timestamp,
	`diasPrazo` int,
	`status` enum('pendente','lida','respondida','vencida','cancelada') NOT NULL DEFAULT 'pendente',
	`prioridade` enum('baixa','media','alta','urgente') NOT NULL DEFAULT 'media',
	`conteudo` text,
	`anexoUrl` varchar(1000),
	`tribunal` varchar(50),
	`vara` varchar(200),
	`comarca` varchar(200),
	`numeroCnj` varchar(30),
	`observacoes` text,
	`conectorId` int,
	`externalId` varchar(200),
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `intimacoes_id` PRIMARY KEY(`id`)
);
